trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.37/quarto-1.9.37-linux-amd64.deb
      sudo dpkg -i quarto-1.9.37-linux-amd64.deb
    displayName: Install Quarto

  - script: quarto render
      echo "=== ROOT ==="
      ls -la
      echo "=== BOOK ==="
      ls -la _book
      echo "=== INDEX ==="
      cat _book/index.html | head
    displayName: Debug Quarto Output

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "_book"
      output_location: ""
      skip_app_build: true
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

