# Indicatoren toevoegen aan de statistiekhub {#sec-indicatoren}

## structuur metadata


Als de geleverde dataset nieuwe indicatoren bevat, moet eerst de bijbehorende `metadata` worden toegevoegd aan de statistiekhub. Dit kan handmatig of geautomatiseerd worden gedaan via een csv-bestand. Zorg dat het bestand voldoet aan de volgende naamgeving: `<datum>_<thema>_indicatoren.csv`, bijvoorbeeld: 
   
`20230208_veiligheid_indicatoren.csv`  
  
Het bestand kan eveneens geupload worden op de volgende site:  
   
`http://statistiekhub.amsterdam.nl/import_export_job/importjob/`  
  
Nadat je bent ingelogd op de website, kan je via de knop `import` het csv-bestand importeren.  
  
- Bij `format` kan je kiezen tussen `csv` of `semicolon csv`. Semicolon geniet de voorkeur.
- Bij `name of model to import` geef je `measure` aan. 
   
Het csv-bestand moet onderstaande attributen bevatten. Sommigen zijn verplicht, anderen optioneel.
  
## Opbouw indicatorenbestand voor de Statistiekhub

::: {style="font-size: 0.8em;"}

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| team              | verantwoordelijk team of afdeling                              | Veiligheid             | verplicht |
| themes            | thema's, miimaal een thema, meerdere thema's scheiden met pipe-symbol            | Economie\| Wonen | min. een  |
: 1 Basis 
  

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| name              | naam van de indicator, is gelijk aan `measure` uit `observations`     | vestr_p                | verplicht |
| label             | korte omschrijving     | aandeel vestigingen in de sector R: cultuur, sport en recreatie (%)       | verplicht |
| definition        | omschrijving van de indicator en methode                       |                        | verplicht |
| unit              | meeteenheid                                                    | percentage             | verplicht |
| decimals          | aantal decimalen voor afronding in publicatietabellen          | 0                      | verplicht |
| source            | minimaal een bron, meerdere bronnen worden gescheiden met het pipe-symbol | LISA\| bewerking O&S   | verplicht |
| temporal_type     | twee opties: "peildatum" of "periode"                          | peildatum              | verplicht |
| sensitive         | boolean: sensitive (TRUE) of niet (FALSE)                      | FALSE                  | verplicht |
: 2 Verplichte velden  
   

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| label_short       | nog kortere omschrijving tbv visualisaties                     | vest. sector R (%)     | verplicht |
| frequency         | mate waarin data geupdate wordt                                | een keer per jaar      | verplicht |
| description       | extra veld voor toelichtingen op indicator of berekening       |                        |           |
| Parent            | veld om hierarchie in indicatoren te definieren                | nog niet actief        |     |
| Dimension         | veld om subset te definieren                                   | nog niet actief        |  |
: 3 Details  
   

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| label_uk          | korte omschrijving engels          | firms in branche R: culture, sports and recreation (%)           | verplicht |
| definition_uk     | beschrijving van de indicator en methode in engels             |                        | verplicht |
| label_uk_short    | nog kortere omschrijving tbv visualisaties                     | firms in branche R (%) | verplicht |
| frequency_uk      | mate waarin data geupdate wordt                                | once every year        | verplicht |
| description_uk    | extra veld voor toelichtingen in engels                        |                        |           |
: 4 vertaling Engels  
  

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| calculation       | formule voor berekende waarde                                  | zie @sec-calc          |           |
| Extra atrr        | json-veld voor styling dashboard                               | zie @sec-attr          |          |
: 5 Product specifiek  
  

| kolomnaam         | toelichting                                                    |notitiewijze            | veplicht  |
|-------------------|----------------------------------------------------------------|------------------------| ----------|
| Deprecated        | veld voor indicatoren die niet meer geupdate worden            | FALSE                  |          |
| Deprecated date   | datum vanaf wanneer de indicator niet meer publiek is          | yyyymmdd               |          |
| Deprecated reason | reden waarom de indicator niet meer publiek gemaakt wordt      | toelichting            |          |
: 6 Vervallen  

:::
  
In de toekomst kan de inicatorenlijst aangevuld worden met onderstaande velden in de Statistiekhub om extra functionaliteiten mogelijk te maken. 
  
- `filter` voor het realiseren van deelverzamelingen (denk aan tabel kerncijfers of tabel veiligheidsmonitor)  
- `dimension` voor het structuren van indicatoren met verschillende dimensies (denk aan herkomst en leeftijd)
- `parent` (voor het koppelen van indicatoren in een hiërarchische structuur)
  
Hoewel geen officiële richtlijn, adviseren wij om de `name` van een indicator aan te laten sluiten op een `thema` en `unit`. Dat betekent dat in de naam met een prefix verwezen kan worden naar het bijbehorende thema en de suffix naar de juiste eenheid. Als de eenheid `aantal` is, gebruik dan geen suffix. 
  
`<afkorting thema>_indicatornaam_<afkorting eenheid>` voorbeeld: `o_havo_p`  
  
Bij de attributen `thema` en `eenheid` worden de thema's gekozen uit voorgedefinieerde lijsten. Deze twee lijsten staan onder de kop `referentie tabellen` in de Statistiekhub. Neem contact op met de beheerder als jouw gewenste thema of eenheid niet in de lijst staat.  
   
## Berekende indicatoren {#sec-calc}  
  
Naast het aanleveren van cijfers over indicatoren bestaat de mogelijkheid om cijfers automatisch te laten uitrekenen, bijvoorbeeld het percentage mannen op de totale bevolking. Deze cijfers worden dan uitgerekend voor indicatoren met dezelfde temporele én ruimtelijke dimensie. Vanzelfsprekend moeten de cijfers van de indicatoren in de rekenformule wel al zijn toegevoegd om te kunnen rekenen. Indien er cijfers van automatisch te berekenen indicatoren zijn aangeleverd, dan hebben deze voorrang op de automatisch berekende cijfers.  
  
Om cijfers automatisch te laten uitrekenen moet in de metadata bij de betreffende indicator de rekenformule worden toegevoegd in het attribuut `calculation`. De rekenformule kent strikte notatieregels:  
  
-   iedere indicator moet beginnen met een "\$"\
-   er moet een spatie tussen ieder element van de rekenformule\
-   indien er in de formule gedeeld met moeten ("/"), dan moet het noemer-deel van de deling tussen "()"\
-   indien een indicator afhankelijk is van een bepaalde periode, dan moet de periode worden omsloten door "\[\]" en de periode worden gekoppeld met een "-". Het wordt gezien als een 'keuze-indicator' en heeft dus maar één "\$"\
  
Hieronder staan twee voorbeeldformules:
  
-   `( \$OSTUDWO / ( \$BEVTOTAAL ) ) \* 100`   
-   `( \$IAO / ( \$\[2009-2016\]\|BEVPOTBBV15_64\|\[2017-2999\]\|BEVPOTBBV15_65 ) ) \* 100`  
  
## Extra attr {#sec-attr}
  
In het veld `Extra attr` kan informatie opgenomen worden voor de styling van de figuren in het Dashboard Kerncijfers op de website van Onderzoek en Statistiek. Daarnaast wordt dit veld gebruikt om extra regels toe te voegen voor het berekenen van de standaarddeviatie. 
  
  
- `{
"BBGA_sort": 250,  
"BBGA_kleurenpalet": 9,  
"BBGA_peildatum": "1 april",  
"BBGA_reference_date": "1 April",  
"BBGA_sd_minimum_bev_totaal": "1000",  
"BBGA_sd_minimum_wvoor_bag": "20" 
}`
  
  
`BBGA_sort` wordt gebruikt voor de volgorde in rolluik indicator van het Dashboard Kerncijfers. Indien bbga_sort niet is ingevuld wordt de alfabetische volgorde aangehouden.  
   
`BBGA_kleurenpalet` bepaalt de kleurschakering in de figuren: 1 is van rood (laag en negatief) naar groen (hoog en positief); 2 van groen (laag en positief) naar rood (hoog en negatief); 9 wordt gebruikt voor absolute waarden. Als er geen data is geleverd op wijkniveau of als er geen Amsterdams gemiddelde is meegegeven dan worden geen standaardafwijkingen berekend en dan worden de stoplichtkleuren vervangen door groentinten.  
  
De data bij `BBGA_peildatum` en `BBGA_reference_date` worden in het dashboard kerncijfers toegevoegd bij de beschrijving van de variabele, bron en definitie.  
  
`BBGA_sd_minimum_bev_totaal` en `BBGA_sd_minimum_wvoor_bag` zijn minimumwaardes van wijken waarop standaarddeviaties berekend worden, wanneer extreme waarden of uitbijters niet meegenomen mogen worden in de berekening.  
  
## dry run en import  
  
Op een vergelijkbare manier als bij het importeren van cijfers worden nu de indicatoren geïmporteerd. Voer eerst een `dry-run` uit en vervolgens een'echte' `import`. De indicatoren zijn nu toegevoegd aan de hub.  